version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-local
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: jason
      MYSQL_PASSWORD: jason1234
    ports:
      - "3306:3306"
    volumes:
        - ./mysql:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongo-local
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: jason
      MONGO_INITDB_ROOT_PASSWORD: jason1234
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db


  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper-local
    restart: always
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-local
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.01
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
