server:
  port: 8081

spring:
  application:
    name: boot-base
  profiles:
    active: local
    group:
      local: common



---
spring:
  config:
    activate:
      on-profile: common
    import:
      - jasypt.yml
      - aes.yml
      - kafka.yml

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - db-local.yml

---
spring:
  config:
    activate:
      on-profile: dev
    import:
        - db-dev.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import:
        - db-prod.yml



