server:
  port: 8081

spring:
  application:
    name: boot-base
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
    import:
      - jasypt.yml
      - db-local.yml

---
spring:
  config:
    activate:
      on-profile: dev
    import:
        - jasypt.yml
        - db-dev.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import:
        - jasypt.yml
        - db-prod.yml


aes:
  key: "Test1234"
